export const USER_ADD_BACTERIA = 'USER_ADD_BACTERIA';
export const USER_DELETE_BACTERIA = 'USER_DELETE_BACTERIA';
export const USER_EDIT_NAME_BACTERIA = 'USER_EDIT_NAME_BACTERIA';
export const USER_GET_BACTERIA = 'USER_GET_BACTERIA';