export const USER_ADD_PROTOCOL = 'USER_ADD_PROTOCOL';
export const USER_DELETE_PROTOCOL = 'USER_DELETE_PROTOCOL';
export const USER_EDIT_NAME_PROTOCOL = 'USER_EDIT_NAME_PROTOCOL';
export const USER_GET_PROTOCOL = 'USER_GET_PROTOCOL';